const companies = [
  {
    id: "neko",
    name: "네코전자",
    ticker: "NEKO",
    sector: "AI·전자",
    ceo: "한유진",
    business: "감정 인식 칩, 교실용 미니 서버, 생활형 AI 단말",
    risk: "보통",
    growthLabel: "매우 높음",
    dividendLabel: "낮음",
    listingStatus: "정상",
    description: "고양이 귀 모양의 홈 AI 단말로 유명해진 전자 기업입니다. 공공 단말 수요와 부품 수급에 따라 기대감이 크게 흔들립니다.",
    hidden: { growth: 88, debt: 34, cashFlow: 63, reputation: 72, innovation: 94, legalRisk: 18, management: 81 }
  },
  {
    id: "bana",
    name: "바나나항공",
    ticker: "BANA",
    sector: "항공",
    ceo: "박도윤",
    business: "저가 항공, 섬 노선, 야간 화물편",
    risk: "높음",
    growthLabel: "보통",
    dividendLabel: "없음",
    listingStatus: "주의",
    description: "노란색 기체와 섬 노선 특화 전략으로 알려진 항공사입니다. 유류비와 교통 정책 변화에 취약합니다.",
    hidden: { growth: 46, debt: 78, cashFlow: 37, reputation: 54, innovation: 42, legalRisk: 43, management: 51 }
  },
  {
    id: "moon",
    name: "달빛식품",
    ticker: "MOON",
    sector: "식품",
    ceo: "정서린",
    business: "야식 키트, 냉동 디저트, 편의점 간편식",
    risk: "낮음",
    growthLabel: "보통",
    dividendLabel: "보통",
    listingStatus: "정상",
    description: "밤 시간대 소비를 겨냥한 간편식을 만드는 방어형 소비 기업입니다. 원재료 가격과 편의점 발주가 중요합니다.",
    hidden: { growth: 58, debt: 32, cashFlow: 78, reputation: 84, innovation: 49, legalRisk: 16, management: 73 }
  },
  {
    id: "whal",
    name: "고래에너지",
    ticker: "WHAL",
    sector: "에너지",
    ceo: "문태오",
    business: "해상 풍력, 항만 배터리, 대형 전력 저장망",
    risk: "보통",
    growthLabel: "높음",
    dividendLabel: "보통",
    listingStatus: "정상",
    description: "항만 전력망과 대형 배터리 사업을 운영합니다. 정책 수주와 금리 변화가 동시에 작용하는 종목입니다.",
    hidden: { growth: 74, debt: 55, cashFlow: 61, reputation: 69, innovation: 71, legalRisk: 31, management: 67 }
  },
  {
    id: "pixl",
    name: "픽셀게임즈",
    ticker: "PIXL",
    sector: "게임",
    ceo: "노가람",
    business: "모바일 RPG, 길드전 리그, 캐릭터 IP",
    risk: "높음",
    growthLabel: "높음",
    dividendLabel: "낮음",
    listingStatus: "정상",
    description: "도트 그래픽 RPG와 길드전 콘텐츠로 충성 유저를 보유한 게임사입니다. 신작 반응이 모든 것을 바꿉니다.",
    hidden: { growth: 72, debt: 41, cashFlow: 49, reputation: 62, innovation: 76, legalRisk: 29, management: 58 }
  },
  {
    id: "mint",
    name: "민트바이오",
    ticker: "MINT",
    sector: "바이오",
    ceo: "오하린",
    business: "피로 회복 패치, 미생물 치료제, 진단 키트",
    risk: "매우 높음",
    growthLabel: "매우 높음",
    dividendLabel: "없음",
    listingStatus: "관찰",
    description: "패치형 치료제 임상 결과에 따라 기대와 공포가 반복되는 바이오 기업입니다. 루머 민감도가 높습니다.",
    hidden: { growth: 91, debt: 63, cashFlow: 24, reputation: 57, innovation: 89, legalRisk: 48, management: 54 }
  },
  {
    id: "iron",
    name: "철갑물류",
    ticker: "IRON",
    sector: "물류",
    ceo: "강무현",
    business: "냉장 물류, 로봇 창고, 고중량 배송",
    risk: "보통",
    growthLabel: "보통",
    dividendLabel: "보통",
    listingStatus: "정상",
    description: "사고가 적고 느리지만 안정적인 물류사입니다. 식품과 바이오 계약 흐름이 실적을 좌우합니다.",
    hidden: { growth: 52, debt: 39, cashFlow: 72, reputation: 76, innovation: 56, legalRisk: 22, management: 70 }
  },
  {
    id: "cldb",
    name: "구름은행",
    ticker: "CLDB",
    sector: "금융",
    ceo: "백시우",
    business: "클라우드 지갑, 게임머니 정산, 소상공인 대출",
    risk: "보통",
    growthLabel: "보통",
    dividendLabel: "높음",
    listingStatus: "정상",
    description: "Market City 소상공인 결제망을 장악한 금융사입니다. 금리, 연체율, 유동성 흐름에 민감합니다.",
    hidden: { growth: 49, debt: 46, cashFlow: 83, reputation: 71, innovation: 52, legalRisk: 26, management: 74 }
  },
  {
    id: "rokt",
    name: "로켓모빌리티",
    ticker: "ROKT",
    sector: "모빌리티",
    ceo: "차이라",
    business: "전기 스쿠터, 자율 셔틀, 배터리 교환소",
    risk: "높음",
    growthLabel: "높음",
    dividendLabel: "없음",
    listingStatus: "관찰",
    description: "자율 셔틀과 배터리 교환소를 실험하는 모빌리티 기업입니다. 안전 인증과 자금 조달이 핵심입니다.",
    hidden: { growth: 82, debt: 72, cashFlow: 31, reputation: 59, innovation: 86, legalRisk: 45, management: 63 }
  },
  {
    id: "mush",
    name: "버섯건설",
    ticker: "MUSH",
    sector: "건설",
    ceo: "임하늘",
    business: "친환경 주거 단지, 지하 상가, 모듈러 주택",
    risk: "보통",
    growthLabel: "낮음",
    dividendLabel: "보통",
    listingStatus: "정상",
    description: "균사체 단열재를 활용하는 건설사입니다. 금리와 정책성 부동산 이벤트에 강하게 반응합니다.",
    hidden: { growth: 39, debt: 67, cashFlow: 45, reputation: 64, innovation: 61, legalRisk: 34, management: 56 }
  },
  {
    id: "lemn",
    name: "레몬클라우드",
    ticker: "LEMN",
    sector: "소프트웨어",
    ceo: "최다정",
    business: "업무용 클라우드, 협업 보드, 데이터 백업",
    risk: "낮음",
    growthLabel: "높음",
    dividendLabel: "낮음",
    listingStatus: "정상",
    description: "중소기업 협업 소프트웨어를 제공하는 구독형 기업입니다. 기관 자금이 선호하는 안정 성장주입니다.",
    hidden: { growth: 77, debt: 25, cashFlow: 74, reputation: 82, innovation: 69, legalRisk: 20, management: 79 }
  },
  {
    id: "sprk",
    name: "스파크패션",
    ticker: "SPRK",
    sector: "소비재",
    ceo: "윤세아",
    business: "스마트 의류, 스트리트 브랜드, 재활용 섬유",
    risk: "보통",
    growthLabel: "보통",
    dividendLabel: "낮음",
    listingStatus: "정상",
    description: "온도에 따라 색이 변하는 재킷으로 유행을 만든 소비재 기업입니다. 광고와 유행 주기가 중요합니다.",
    hidden: { growth: 57, debt: 36, cashFlow: 58, reputation: 77, innovation: 66, legalRisk: 18, management: 60 }
  },
  {
    id: "aura",
    name: "오로라미디어",
    ticker: "AURA",
    sector: "미디어",
    ceo: "서이준",
    business: "가상 예능, 스트리밍 채널, 팬덤 데이터",
    risk: "보통",
    growthLabel: "높음",
    dividendLabel: "없음",
    listingStatus: "정상",
    description: "가상 출연자 예능과 팬덤 데이터를 판매하는 미디어 기업입니다. 구독 이탈률과 콘텐츠 평판이 중요합니다.",
    hidden: { growth: 69, debt: 44, cashFlow: 53, reputation: 68, innovation: 73, legalRisk: 37, management: 62 }
  },
  {
    id: "shld",
    name: "방패보안",
    ticker: "SHLD",
    sector: "보안",
    ceo: "도민재",
    business: "금융 보안, 게임 계정 보호, 침해 대응 센터",
    risk: "낮음",
    growthLabel: "높음",
    dividendLabel: "낮음",
    listingStatus: "정상",
    description: "게임 계정과 금융 지갑을 지키는 보안 기업입니다. 해킹 이슈가 생기면 방어주처럼 주목받습니다.",
    hidden: { growth: 71, debt: 21, cashFlow: 68, reputation: 80, innovation: 74, legalRisk: 24, management: 76 }
  },
  {
    id: "blue",
    name: "푸른소재",
    ticker: "BLUE",
    sector: "친환경소재",
    ceo: "남가온",
    business: "해조류 플라스틱, 친환경 포장재, 균사체 필름",
    risk: "보통",
    growthLabel: "높음",
    dividendLabel: "낮음",
    listingStatus: "정상",
    description: "해조류 기반 포장재를 만드는 소재 기업입니다. 식품과 건설 업종의 공급망 변화가 기회입니다.",
    hidden: { growth: 73, debt: 48, cashFlow: 42, reputation: 75, innovation: 81, legalRisk: 28, management: 64 }
  },
  {
    id: "mrbl",
    name: "마블스쿨",
    ticker: "MRBL",
    sector: "교육",
    ceo: "김유나",
    business: "게임형 학습 앱, AI 튜터, 학교 운영 플랫폼",
    risk: "보통",
    growthLabel: "높음",
    dividendLabel: "없음",
    listingStatus: "신규상장 후보",
    description: "Market City 학생들이 쓰는 게임형 학습 앱을 운영합니다. 공공 교육 예산과 개인정보 이슈가 동시에 작용합니다.",
    hidden: { growth: 79, debt: 52, cashFlow: 36, reputation: 70, innovation: 82, legalRisk: 41, management: 59 }
  }
];

function battleCompany(id, name, ticker, sector, ceo, business, risk, growthLabel, dividendLabel, listingStatus, description, hidden) {
  return { id, name, ticker, sector, ceo, business, risk, growthLabel, dividendLabel, listingStatus, description, hidden };
}

// Market Battle 본게임 종목 풀과 맞춘 정보 포털용 기업 데이터입니다.
const marketBattleCompanies = [
  battleCompany("mb-dalbit", "달빛전자", "DALB", "AI·전자", "윤채원", "생활 가전 회로, 저전력 센서, 소형 디스플레이", "보통", "높음", "낮음", "본게임 종목", "본게임에서 초반 랜덤 종목으로 등장할 수 있는 전자 기업입니다. 제품 기대와 부품 원가 부담이 자주 충돌합니다.", { growth: 72, debt: 38, cashFlow: 61, reputation: 69, innovation: 74, legalRisk: 22, management: 66 }),
  battleCompany("mb-cloudsoft", "구름소프트", "CLDS", "소프트웨어", "하도겸", "클라우드 협업툴, 게임 룸 서버, 백업 콘솔", "낮음", "높음", "낮음", "본게임 종목", "방 코드와 실시간 데이터 흐름을 다루는 소프트웨어 기업입니다. 안정성 평판은 강하지만 성장 기대가 가격에 먼저 반영되기 쉽습니다.", { growth: 78, debt: 26, cashFlow: 72, reputation: 83, innovation: 70, legalRisk: 18, management: 77 }),
  battleCompany("mb-bolt", "번개모빌리티", "BOLT", "모빌리티", "차서율", "도심 전동 카트, 배터리 스테이션, 빠른 배송 셔틀", "높음", "높음", "없음", "본게임 종목", "이동 수요가 붙으면 빠르게 주목받지만 안전 인증과 현금 소모가 동시에 따라오는 모빌리티 기업입니다.", { growth: 84, debt: 73, cashFlow: 34, reputation: 58, innovation: 82, legalRisk: 42, management: 61 }),
  battleCompany("mb-seafood", "바다식품", "BADA", "식품", "송이안", "냉동 도시락, 해조 간식, 급식 납품", "낮음", "보통", "보통", "본게임 종목", "실시간 체결 목록에서 방어주처럼 자주 거론되는 식품 기업입니다. 원가와 납품 계약 조건에 따라 해석이 갈립니다.", { growth: 55, debt: 29, cashFlow: 81, reputation: 76, innovation: 46, legalRisk: 15, management: 72 }),
  battleCompany("mb-starbio", "별빛바이오", "STAR", "바이오", "류다현", "피부 재생 패치, 야간 진단 키트, 미세 캡슐 치료제", "매우 높음", "매우 높음", "없음", "본게임 종목", "작은 임상 단서에도 가격 기대가 커지는 바이오 기업입니다. 루머와 공시의 간격이 가장 위험한 구간입니다.", { growth: 92, debt: 60, cashFlow: 26, reputation: 56, innovation: 90, legalRisk: 49, management: 55 }),
  battleCompany("mb-bitegame", "한입게임즈", "BITE", "게임", "문태린", "짧은 판 모바일 게임, 길드 이벤트, 캐릭터 상점", "보통", "높음", "없음", "본게임 종목", "짧고 빠른 게임성을 앞세운 게임사입니다. 이벤트 매출은 강하지만 흥행 수명이 짧다는 평가도 함께 받습니다.", { growth: 74, debt: 37, cashFlow: 54, reputation: 65, innovation: 71, legalRisk: 28, management: 60 }),
  battleCompany("mb-greenenergy", "초록에너지", "GREN", "에너지", "정해솔", "소형 태양광, 학교 전력망, 배터리 재활용", "보통", "높음", "보통", "본게임 종목", "정책 수혜가 붙을 때 강하지만 설비 투자 부담도 커지는 에너지 기업입니다.", { growth: 76, debt: 58, cashFlow: 57, reputation: 70, innovation: 73, legalRisk: 30, management: 68 }),
  battleCompany("mb-cotton", "솜사탕유통", "COTN", "소비재", "나유리", "간식 유통, 팝업 매장, 캐릭터 굿즈", "보통", "보통", "낮음", "본게임 종목", "밈과 유행에 민감한 유통 기업입니다. 관심은 빠르게 붙지만 재고 부담이 뒤늦게 확인됩니다.", { growth: 62, debt: 41, cashFlow: 59, reputation: 74, innovation: 55, legalRisk: 20, management: 58 }),
  battleCompany("mb-rainbowair", "무지개항공", "RAIN", "항공", "기준호", "저가 항공, 관광 노선, 야간 화물", "높음", "보통", "없음", "본게임 종목", "본게임 화면에서 변동성이 크게 보이는 항공 기업입니다. 유류비와 노선 규제, 단기 수급이 동시에 흔듭니다.", { growth: 48, debt: 76, cashFlow: 39, reputation: 53, innovation: 43, legalRisk: 44, management: 50 }),
  battleCompany("mb-acorn", "도토리금융", "ACRN", "금융", "오지훈", "소액 대출, 게임머니 정산, 랭킹 보상 지갑", "보통", "보통", "높음", "본게임 종목", "금리와 유동성 뉴스에 민감한 금융 기업입니다. 안정적 현금흐름과 연체율 우려가 함께 보입니다.", { growth: 51, debt: 45, cashFlow: 82, reputation: 68, innovation: 54, legalRisk: 27, management: 73 }),
  battleCompany("mb-galaxychip", "은하반도체", "GLXY", "AI·전자", "강루아", "추론 칩, 센서 패키징, 저전력 메모리", "높음", "매우 높음", "낮음", "본게임 종목", "AI 테마가 강할 때 가장 먼저 주목받지만 수요 선반영과 공급 병목이 가격을 흔듭니다.", { growth: 89, debt: 52, cashFlow: 45, reputation: 67, innovation: 92, legalRisk: 31, management: 65 }),
  battleCompany("mb-softchem", "포근화학", "SOFT", "친환경소재", "한세민", "완충 소재, 저자극 접착제, 포장 필름", "보통", "보통", "보통", "본게임 종목", "소재 가격과 납품처 변화에 따라 천천히 재평가되는 화학 기업입니다.", { growth: 57, debt: 43, cashFlow: 64, reputation: 71, innovation: 60, legalRisk: 26, management: 67 }),
  battleCompany("mb-heartrobot", "두근로보틱스", "HART", "모빌리티", "백로운", "매장 로봇, 배송 보조 팔, 자동 충전 모듈", "높음", "매우 높음", "없음", "본게임 종목", "로봇과 모빌리티 사이에 걸친 고성장 기업입니다. 계약 뉴스가 커도 양산 능력이 확인되어야 합니다.", { growth: 88, debt: 69, cashFlow: 33, reputation: 63, innovation: 91, legalRisk: 39, management: 62 }),
  battleCompany("mb-dawnent", "새벽엔터", "DAWN", "미디어", "서라희", "심야 콘서트, 가상 아이돌, 팬덤 데이터", "보통", "높음", "없음", "본게임 종목", "팬덤 심리와 구독 지표가 먼저 움직이는 엔터 기업입니다. 좋은 반응도 이미 알려졌다면 가격 반응은 제한될 수 있습니다.", { growth: 73, debt: 46, cashFlow: 50, reputation: 66, innovation: 75, legalRisk: 34, management: 59 }),
  battleCompany("mb-whalemul", "고래물산", "WMLS", "물류", "공태오", "대형 창고, 항만 보관, 전략 물자 유통", "보통", "보통", "보통", "본게임 종목", "거래대금이 커지는 라운드에서 수급 해석이 자주 붙는 물류 기업입니다. 안정성과 큰손 루머가 동시에 따라옵니다.", { growth: 54, debt: 42, cashFlow: 73, reputation: 72, innovation: 51, legalRisk: 24, management: 69 }),
  battleCompany("mb-dandelion", "민들레제약", "DNDR", "바이오", "민서윤", "알레르기 치료제, 호흡기 패치, 약국 공급망", "높음", "높음", "낮음", "본게임 종목", "제약 방어성과 바이오 기대가 섞인 기업입니다. 임상보다 약국 발주 데이터가 먼저 힌트를 줄 때가 있습니다.", { growth: 75, debt: 50, cashFlow: 48, reputation: 69, innovation: 78, legalRisk: 38, management: 63 }),
  battleCompany("ipo-rockettech", "떡상테크", "TTEK", "AI·전자", "장도현", "초단기 AI 분석기, 미니 서버, 교육용 단말", "매우 높음", "매우 높음", "없음", "IPO 후보", "공모주 과열 라운드에서 이름이 자주 도는 신규상장 후보입니다. 이름값 때문에 기대가 먼저 붙는 편입니다.", { growth: 94, debt: 61, cashFlow: 28, reputation: 58, innovation: 92, legalRisk: 36, management: 57 }),
  battleCompany("ipo-unicornsoft", "유니콘소프트", "UNIC", "소프트웨어", "채다인", "방 관리 SaaS, 실시간 채팅, 점수판 API", "높음", "매우 높음", "없음", "IPO 후보", "상장 전부터 기관 관심이 있다는 말이 돌지만 매출 검증은 아직 부족한 소프트웨어 후보입니다.", { growth: 90, debt: 44, cashFlow: 35, reputation: 72, innovation: 84, legalRisk: 28, management: 66 }),
  battleCompany("ipo-miraemobil", "미래모빌", "MIRA", "모빌리티", "차재민", "무인 셔틀, 소형 배터리, 교내 이동 플랫폼", "매우 높음", "높음", "없음", "IPO 후보", "상장 전 기대와 안전 인증 리스크가 정면으로 충돌하는 모빌리티 후보입니다.", { growth: 86, debt: 70, cashFlow: 30, reputation: 60, innovation: 88, legalRisk: 46, management: 58 }),
  battleCompany("ipo-firstbio", "첫걸음바이오", "STEP", "바이오", "노하은", "초기 진단 키트, 저가 임상 플랫폼, 샘플 분석", "매우 높음", "매우 높음", "없음", "IPO 후보", "검증 단계가 짧아 정보 공백이 큰 바이오 IPO 후보입니다. 루머가 가장 잘 번지는 종목군입니다.", { growth: 91, debt: 65, cashFlow: 22, reputation: 54, innovation: 87, legalRisk: 52, management: 52 }),
  battleCompany("ipo-starenergy", "샛별에너지", "SENE", "에너지", "고아린", "도시형 ESS, 야간 전력 거래, 초소형 충전소", "높음", "높음", "없음", "IPO 후보", "에너지 쇼크 라운드에서 수혜와 원가 부담이 동시에 붙는 신규 후보입니다.", { growth: 81, debt: 62, cashFlow: 41, reputation: 66, innovation: 79, legalRisk: 33, management: 61 }),
  battleCompany("ipo-rookiegames", "루키게임즈", "ROOK", "게임", "최이든", "신규 모바일 퍼즐, 스트리머 협업, 시즌 패스", "높음", "높음", "없음", "IPO 후보", "신작 지표가 좋으면 빠르게 달아오르지만 이용자 잔존율 확인 전까지 판단이 어렵습니다.", { growth: 82, debt: 39, cashFlow: 42, reputation: 64, innovation: 73, legalRisk: 25, management: 56 }),
  battleCompany("ipo-mythent", "신화엔터", "MYTH", "미디어", "은도윤", "가상 공연장, 팬덤 멤버십, IP 라이선스", "보통", "높음", "없음", "IPO 후보", "팬덤 구매력은 강하지만 상장 이후 락업 물량 우려가 따라붙는 엔터 후보입니다.", { growth: 78, debt: 47, cashFlow: 47, reputation: 75, innovation: 77, legalRisk: 30, management: 62 }),
  battleCompany("ipo-quantumchip", "퀀텀반도체", "QNTM", "AI·전자", "권태성", "양자 보조 칩, 고성능 패키징, 연구용 보드", "매우 높음", "매우 높음", "없음", "IPO 후보", "기술 설명은 화려하지만 매출 전환 시점이 멀어 해석이 갈리는 반도체 IPO 후보입니다.", { growth: 95, debt: 67, cashFlow: 20, reputation: 61, innovation: 96, legalRisk: 42, management: 54 })
];

companies.push(...marketBattleCompanies);

const marketState = {
  sentiment: "중립",
  liquidity: 62,
  volatility: 58,
  interestRate: 3.25,
  inflation: 54,
  institutionPower: 64,
  whalePower: 47,
  rumorReliability: 44,
  policyPressure: 52,
  creditStress: 41,
  description: "유동성은 아직 남아 있지만 금리와 정책 변수 때문에 자금이 업종별로 빠르게 이동하고 있습니다. 호재가 곧바로 상승으로 이어지지 않고, 악재가 오히려 매물 소화 신호로 해석되는 장면도 나옵니다."
};

const sectorStates = {
  "AI·전자": { mood: "과열", capitalFlow: 78, demand: 86, policy: 62, supplyStress: 43 },
  "항공": { mood: "냉각", capitalFlow: 31, demand: 44, policy: 73, supplyStress: 69 },
  "식품": { mood: "방어적 강세", capitalFlow: 59, demand: 72, policy: 28, supplyStress: 51 },
  "에너지": { mood: "정책 대기", capitalFlow: 66, demand: 69, policy: 79, supplyStress: 58 },
  "게임": { mood: "혼조", capitalFlow: 48, demand: 57, policy: 34, supplyStress: 32 },
  "바이오": { mood: "고위험 관망", capitalFlow: 52, demand: 61, policy: 47, supplyStress: 37 },
  "물류": { mood: "완만한 회복", capitalFlow: 55, demand: 63, policy: 35, supplyStress: 46 },
  "금융": { mood: "금리 민감", capitalFlow: 50, demand: 49, policy: 66, supplyStress: 29 },
  "모빌리티": { mood: "투자 심사", capitalFlow: 45, demand: 64, policy: 59, supplyStress: 55 },
  "건설": { mood: "정책 저울질", capitalFlow: 38, demand: 42, policy: 72, supplyStress: 67 },
  "소프트웨어": { mood: "기관 선호", capitalFlow: 73, demand: 76, policy: 30, supplyStress: 22 },
  "소비재": { mood: "테마 순환", capitalFlow: 53, demand: 58, policy: 24, supplyStress: 39 },
  "미디어": { mood: "구독 점검", capitalFlow: 46, demand: 56, policy: 32, supplyStress: 35 },
  "보안": { mood: "방어 수요", capitalFlow: 61, demand: 70, policy: 44, supplyStress: 23 },
  "친환경소재": { mood: "수주 기대", capitalFlow: 57, demand: 67, policy: 68, supplyStress: 49 },
  "교육": { mood: "예산 관망", capitalFlow: 49, demand: 62, policy: 71, supplyStress: 26 }
};

const eventTypes = [
  "IPO", "신규상장", "거래정지", "관리종목", "상장폐지 심사", "상장폐지", "인수합병", "회사분할",
  "유상증자", "무상증자", "배당", "실적 발표", "신제품 발표", "정책 발표", "대형 시장 이벤트"
];

const newsTemplates = [
  { id: "n001", type: "수요", tone: "positive", title: "{company}, {sector} 주문 잔고가 예상보다 빠르게 증가", body: "{sector} 업종에 자금이 다시 유입되는 가운데 {company}의 신규 문의가 늘었습니다. 다만 단기 차익 매물이 동시에 관측됩니다." },
  { id: "n002", type: "마진", tone: "negative", title: "{company}, 원가 부담 재부각으로 마진 방어 시험대", body: "{company}의 비용 구조가 시장 관심사로 떠올랐습니다. 투자자들은 매출 성장보다 현금흐름의 지속성을 확인하려 합니다." },
  { id: "n003", type: "정책", tone: "mixed", title: "Market City 정책 초안 공개, {sector} 업종 해석 엇갈려", body: "정책 문구가 모호해 기관과 개인의 반응이 갈립니다. {company}에는 기회와 규제 부담이 동시에 반영될 수 있습니다." },
  { id: "n004", type: "기관", tone: "positive", title: "기관 자금, {company} 포함 안정 성장주로 일부 이동", body: "유동성은 줄지 않았지만 공격적 종목보다 현금흐름이 보이는 기업으로 자금이 옮겨가는 모습입니다." },
  { id: "n005", type: "고래", tone: "mixed", title: "대형 플레이어 매수설에 {company} 변동성 확대", body: "고래 계정의 움직임이 포착됐다는 말이 돌지만 실제 매수인지 포지션 정리인지는 불분명합니다." },
  { id: "n006", type: "루머검증", tone: "mixed", title: "{company} 관련 루머 확산, 회사는 확인 거부", body: "시장에서는 기대가 앞서지만 확인된 문서는 없습니다. 신뢰도보다 자금 흐름이 먼저 반응하는 구간입니다." },
  { id: "n007", type: "실적", tone: "positive", title: "{company}, 예비 매출 지표 개선으로 실적 기대 재점화", body: "공식 실적은 아직 나오지 않았지만 선행 지표가 개선됐다는 해석이 늘었습니다. 기대가 높아진 만큼 실망 위험도 커졌습니다." },
  { id: "n008", type: "실적", tone: "negative", title: "{company}, 비용 증가 경고에 투자 심리 흔들", body: "성장 투자가 이어지며 단기 손익 부담이 커졌습니다. 일부 투자자는 악재 노출을 매수 기회로 해석합니다." },
  { id: "n009", type: "제품", tone: "positive", title: "{company} 신제품 공개 임박, 사전 반응은 우호적", body: "제품 완성도보다 공급 가능 물량이 핵심으로 떠올랐습니다. 수요가 좋아도 납품 지연이 있으면 반응은 달라질 수 있습니다." },
  { id: "n010", type: "제품", tone: "negative", title: "{company} 신제품 후기 엇갈려, 초기 기대 일부 후퇴", body: "핵심 이용자 반응이 갈리면서 단기 방향성이 불안정해졌습니다. 낮아진 기대가 오히려 부담을 줄였다는 시각도 있습니다." },
  { id: "n011", type: "계약", tone: "positive", title: "{company}, Market City 공급망 계약 후보로 부상", body: "확정 계약은 아니지만 제안서 평가에서 높은 점수를 받았다는 관측이 나옵니다. 경쟁사 조건이 변수입니다." },
  { id: "n012", type: "계약", tone: "negative", title: "{company}, 대형 계약 일정 지연 가능성 제기", body: "계약 지연은 단기 악재지만 조건 재협상으로 마진이 좋아질 수 있다는 반대 해석도 있습니다." },
  { id: "n013", type: "IPO", tone: "mixed", title: "{sector} 예비 IPO 등장, 기존 상장사 {company}에 비교 압력", body: "새 후보 기업이 업종 밸류에이션을 흔들고 있습니다. 비교 대상이 생기면 프리미엄과 할인 요인이 동시에 생깁니다." },
  { id: "n014", type: "신규상장", tone: "mixed", title: "신규상장 후보 증가, {sector} 자금 분산 우려", body: "시장 관심이 넓어지면 유동성은 늘 수 있지만 기존 종목의 집중 매수는 약해질 수 있습니다." },
  { id: "n015", type: "거래정지", tone: "negative", title: "{sector} 업종 일부 종목 거래정지 검토설, {company}도 경계감", body: "직접 대상은 확인되지 않았지만 같은 업종이라는 이유로 위험 프리미엄이 높아졌습니다." },
  { id: "n016", type: "관리종목", tone: "negative", title: "관리종목 지정 우려 확산, 취약 재무 기업 선별 장세", body: "부채와 현금흐름이 약한 기업에 매도 압력이 집중됩니다. 다만 과매도 이후 반등을 노리는 자금도 있습니다." },
  { id: "n017", type: "상장폐지 심사", tone: "negative", title: "상장폐지 심사 기준 강화 예고, {company} 재무 안정성 주목", body: "심사 기준 강화는 시장 전체에 긴장감을 주지만 우량 기업에는 상대적 프리미엄을 만들 수 있습니다." },
  { id: "n018", type: "상장폐지", tone: "negative", title: "상장폐지 사례 발생 후 위험 회피 심리 확대", body: "직접 관련 기업이 아니어도 시장은 법적리스크와 현금흐름을 다시 가격에 반영하고 있습니다." },
  { id: "n019", type: "인수합병", tone: "positive", title: "{company}, 인수합병 후보군에 포함됐다는 관측", body: "프리미엄 기대가 생겼지만 실제 협상 여부는 불명확합니다. 부채 부담이 큰 기업일수록 조건이 중요합니다." },
  { id: "n020", type: "인수합병", tone: "mixed", title: "{company} 인수합병설, 시너지보다 가격 부담 논쟁", body: "인수 대상의 기술은 매력적이지만 자금 조달 방식에 따라 기존 주주 반응은 달라질 수 있습니다." },
  { id: "n021", type: "회사분할", tone: "mixed", title: "{company}, 회사분할 가능성 거론에 가치 재평가 기대", body: "성장 사업과 안정 사업을 나누면 가치가 드러날 수 있지만 단기 비용과 지배구조 논쟁도 함께 생깁니다." },
  { id: "n022", type: "유상증자", tone: "negative", title: "{company}, 유상증자 가능성에 희석 우려 부상", body: "자금 조달은 성장 투자에 필요하지만 발행 조건이 나쁘면 단기 투자 심리는 약해질 수 있습니다." },
  { id: "n023", type: "무상증자", tone: "positive", title: "{company}, 무상증자 기대감으로 거래량 증가", body: "무상증자는 기업 가치를 직접 높이지 않지만 유동성과 관심을 키울 수 있습니다. 과열 신호도 함께 확인됩니다." },
  { id: "n024", type: "배당", tone: "positive", title: "{company}, 배당 확대 기대에 방어 매수 유입", body: "금리 불확실성 속에서 현금 환원 기대가 있는 기업이 상대적으로 주목받고 있습니다." },
  { id: "n025", type: "배당", tone: "negative", title: "{company}, 배당 여력 논쟁에 보수적 해석 증가", body: "현금흐름이 충분한지에 대한 의문이 커졌습니다. 배당 기대가 낮아지면 성장 투자 여지가 커진다는 해석도 있습니다." },
  { id: "n026", type: "평판", tone: "negative", title: "{company}, 이용자 불만 증가로 평판 지표 흔들", body: "서비스 품질 논란이 매출에 바로 연결될지는 불확실하지만 투자 심리는 먼저 반응하고 있습니다." },
  { id: "n027", type: "평판", tone: "positive", title: "{company}, 브랜드 호감도 반등으로 소비 지표 개선", body: "평판 개선은 실적보다 늦게 확인됩니다. 시장은 먼저 기대를 반영하려는 모습입니다." },
  { id: "n028", type: "법적리스크", tone: "negative", title: "{company}, 약관 조사 가능성에 법적리스크 재부각", body: "조사 여부가 확정되지는 않았지만 법적리스크가 높은 기업에는 할인 요인이 될 수 있습니다." },
  { id: "n029", type: "경영진", tone: "positive", title: "{company} 경영진, 비용 통제 계획 발표 후 신뢰 회복 시도", body: "계획 자체보다 실행력이 관건입니다. 시장은 관리 능력 개선 여부를 다음 공시에서 확인하려 합니다." },
  { id: "n030", type: "경영진", tone: "negative", title: "{company} 경영진 발언 혼선, 단기 불확실성 확대", body: "성장 전략의 방향은 유지됐지만 표현이 엇갈려 투자자 해석이 분산됐습니다." },
  { id: "n031", type: "자금흐름", tone: "positive", title: "{sector} 업종으로 단기 자금 회귀, {company} 수혜 기대", body: "시장 심리가 완전히 좋아진 것은 아니지만 유동성 일부가 성장 업종으로 이동했습니다." },
  { id: "n032", type: "자금흐름", tone: "negative", title: "{sector} 업종 차익실현 증가, {company}도 매물 압력", body: "상승 피로가 누적되며 좋은 뉴스에도 매도가 나올 수 있는 구간입니다." },
  { id: "n033", type: "신용", tone: "negative", title: "{company}, 신용 매수 과열 구간 진입 경고", body: "투자 심리는 강하지만 레버리지 비중이 높아 작은 악재에도 변동성이 커질 수 있습니다." },
  { id: "n034", type: "신용", tone: "positive", title: "{company}, 신용 부담 완화 후 수급 안정 기대", body: "강제 매도 위험이 줄었다는 평가가 나옵니다. 그러나 신규 매수세가 따라붙을지는 아직 불확실합니다." },
  { id: "n035", type: "노동", tone: "negative", title: "{company}, 근무 교대 협상 난항으로 생산 일정 불확실", body: "생산 차질 가능성이 부각됐지만 협상 타결 시 지연 우려가 빠르게 해소될 수 있습니다." },
  { id: "n036", type: "안전", tone: "negative", title: "{company}, 안전 점검 이슈로 인증 일정 재검토", body: "안전 문제는 단기 신뢰도에 민감합니다. 실제 결함인지 절차상 보완인지는 확인이 필요합니다." },
  { id: "n037", type: "안전", tone: "positive", title: "{company}, 안전 인증 예비 통과 소식에 불확실성 완화", body: "최종 인증은 남았지만 가장 큰 리스크가 낮아졌다는 해석이 나옵니다." },
  { id: "n038", type: "공급망", tone: "negative", title: "{company}, 핵심 부품 조달 지연 가능성 부상", body: "수요가 좋아도 공급이 따라오지 못하면 실적 반영 시점이 뒤로 밀릴 수 있습니다." },
  { id: "n039", type: "공급망", tone: "positive", title: "{company}, 대체 공급망 확보로 납품 안정성 개선", body: "공급망 리스크가 낮아지면 높은 수요가 실적으로 이어질 가능성이 커집니다." },
  { id: "n040", type: "대체재", tone: "mixed", title: "{sector} 대체재 등장, {company} 프리미엄 시험대", body: "경쟁이 늘면 가격 압박이 생기지만 시장 전체 규모가 커지는 효과도 있습니다." },
  { id: "n041", type: "데이터", tone: "positive", title: "{company}, 이용 데이터 개선으로 숨은 성장성 재평가", body: "매출보다 먼저 움직이는 이용 지표가 개선됐습니다. 다만 유료 전환까지 이어지는지는 아직 힌트 수준입니다." },
  { id: "n042", type: "데이터", tone: "negative", title: "{company}, 이용자 체류시간 둔화로 성장 속도 논쟁", body: "성장률 둔화는 악재지만 기대치가 낮아진 뒤에는 작은 개선도 크게 반응할 수 있습니다." },
  { id: "n043", type: "정책", tone: "positive", title: "보조금 재배치 논의, {company}에 의외의 수혜 가능성", body: "정책 방향이 확정되지 않았지만 기존 우려와 다른 수혜 경로가 거론됩니다." },
  { id: "n044", type: "정책", tone: "negative", title: "감독 강화 발언 이후 {sector} 업종 밸류 할인 확대", body: "감독 강화는 성장 기대를 낮출 수 있습니다. 하지만 투명한 기업에는 오히려 신뢰 프리미엄이 생길 수 있습니다." },
  { id: "n045", type: "시장심리", tone: "mixed", title: "탐욕 지표 상승에도 {company} 주가는 방향성 탐색", body: "시장 심리는 강하지만 이미 반영된 기대가 높아 무조건적인 상승으로 이어지지 않습니다." },
  { id: "n046", type: "시장심리", tone: "mixed", title: "공포 지표 확대 속 {company} 저가 매수 대기세 확인", body: "악재가 많아도 가격에 먼저 반영됐다고 보는 자금이 일부 들어오고 있습니다." },
  { id: "n047", type: "경쟁", tone: "negative", title: "{company}, 경쟁사 가격 인하로 단기 점유율 압박", body: "가격 경쟁은 마진을 압박하지만 장기적으로 약한 경쟁사를 밀어내는 계기가 될 수도 있습니다." },
  { id: "n048", type: "경쟁", tone: "positive", title: "{company}, 경쟁사 공급 차질 속 반사 수요 기대", body: "반사 수요가 일시적인지 구조적인지에 따라 시장 반응은 크게 달라집니다." },
  { id: "n049", type: "재무", tone: "positive", title: "{company}, 현금흐름 개선 신호에 재무 우려 완화", body: "부채가 남아 있어도 현금흐름이 돌아서면 시장은 위험을 다시 계산합니다." },
  { id: "n050", type: "재무", tone: "negative", title: "{company}, 단기 차입 증가로 재무 안정성 논쟁", body: "차입은 부담이지만 성장 투자 목적이면 해석이 갈릴 수 있습니다. 다음 일정이 중요합니다." },
  { id: "n051", type: "테마", tone: "positive", title: "{sector} 테마 재점화, {company}가 중심 후보로 거론", body: "테마 자금은 빠르게 들어오고 빠르게 빠져나갑니다. 기본 체력과 수급 피로를 함께 봐야 합니다." },
  { id: "n052", type: "테마", tone: "negative", title: "{sector} 테마 과열 경고, {company} 추격 매수 부담", body: "좋은 재료가 남아 있어도 과열 구간에서는 작은 실망이 크게 반영될 수 있습니다." },
  { id: "n053", type: "협업", tone: "positive", title: "{company}, 다른 업종과의 공동 프로젝트 준비설", body: "협업은 새로운 매출 경로를 만들 수 있지만 실제 계약 구조가 공개되기 전까지는 기대에 가깝습니다." },
  { id: "n054", type: "회계", tone: "negative", title: "{company}, 매출 인식 방식 질의에 보수적 시각 증가", body: "회계 질의는 당장 문제가 아니라도 신뢰도를 흔듭니다. 명확한 해명이 나오면 빠르게 해소될 수 있습니다." },
  { id: "n055", type: "수급", tone: "mixed", title: "{company}, 좋은 재료에도 매도 우위 관측", body: "재료 자체는 우호적이지만 먼저 들어온 자금의 차익실현이 강해 주가 반응은 엇갈릴 수 있습니다." },
  { id: "n056", type: "수급", tone: "mixed", title: "{company}, 악재 노출 후 오히려 매수세 유입", body: "불확실성이 공개되자 대기 자금이 움직였습니다. 악재의 크기보다 해소 속도가 더 중요해졌습니다." }
];

const rumorTemplates = [
  { id: "r001", type: "계약", tone: "positive", title: "{company}, 비공개 공급 계약 최종 서명 직전이라는 말", body: "계약서 초안이 돌았다는 주장이 있지만 발신자는 확인되지 않았습니다." },
  { id: "r002", type: "임상", tone: "positive", title: "{company}, 내부 테스트 지표가 목표치를 넘겼다는 소문", body: "관련 인력이 늘었다는 관측이 근거입니다. 실제 지표와 연결되는지는 알 수 없습니다." },
  { id: "r003", type: "규제", tone: "negative", title: "{company}, 감독기관 질의서를 받았다는 게시글 확산", body: "질의서는 흔한 절차일 수 있습니다. 시장은 법적리스크가 큰 기업부터 의심합니다." },
  { id: "r004", type: "고래", tone: "mixed", title: "고래 계정이 {company} 물량을 모은다는 추적글", body: "체결 패턴만으로는 매집과 분산을 구분하기 어렵습니다." },
  { id: "r005", type: "기관", tone: "positive", title: "기관 모델 포트폴리오에 {company}가 편입됐다는 말", body: "정식 리밸런싱 자료는 없습니다. 다만 수급은 이미 민감하게 반응합니다." },
  { id: "r006", type: "인수합병", tone: "positive", title: "{company}, 인수합병 티저 문서에 이름이 있었다는 주장", body: "문서 형식은 그럴듯하지만 가격과 상대방은 전혀 확인되지 않았습니다." },
  { id: "r007", type: "회사분할", tone: "mixed", title: "{company}, 성장 사업부 분할을 검토한다는 말", body: "가치 재평가 기대와 지배구조 부담이 동시에 거론됩니다." },
  { id: "r008", type: "유상증자", tone: "negative", title: "{company}, 장 마감 후 유상증자를 준비한다는 루머", body: "자금 조달 담당자 미팅이 근거로 제시됐지만 목적은 확인되지 않았습니다." },
  { id: "r009", type: "무상증자", tone: "positive", title: "{company}, 무상증자 검토 문구가 이사회 자료에 있었다는 소문", body: "실제 결의 여부보다 단기 관심을 끌 수 있는 재료입니다." },
  { id: "r010", type: "배당", tone: "positive", title: "{company}, 특별 배당 가능성이 내부 채널에서 언급됐다는 말", body: "현금흐름이 뒷받침되어야 하며, 기대가 과하면 발표 후 실망이 생길 수 있습니다." },
  { id: "r011", type: "거래정지", tone: "negative", title: "{company}, 거래정지 사전 점검 명단에 올랐다는 괴소문", body: "근거가 약하지만 공포 장세에서는 이런 글도 가격을 흔듭니다." },
  { id: "r012", type: "관리종목", tone: "negative", title: "{company}, 관리종목 지정 가능성을 언급한 익명 리포트", body: "익명 리포트는 틀릴 때가 많지만 부채가 높은 기업에는 부담으로 작용합니다." },
  { id: "r013", type: "상장폐지 심사", tone: "negative", title: "{company}, 상장폐지 심사 예비 검토설", body: "법적리스크와 현금흐름이 약할수록 시장은 과민 반응할 수 있습니다." },
  { id: "r014", type: "상장폐지", tone: "negative", title: "{company}, 상장폐지 가능성이라는 자극적 글 확산", body: "확인된 사실은 없습니다. 공포를 키우기 위한 글일 가능성도 있습니다." },
  { id: "r015", type: "신규상장", tone: "mixed", title: "{sector} 신규상장 후보가 {company} 고객을 빼앗는다는 말", body: "신규상장은 위협이면서 업종 관심을 키우는 재료이기도 합니다." },
  { id: "r016", type: "IPO", tone: "mixed", title: "{company} 협력사가 IPO를 준비한다는 소문", body: "협력사 가치가 올라가면 공급 조건이 바뀔 수 있어 해석이 갈립니다." },
  { id: "r017", type: "CEO", tone: "negative", title: "{company} 핵심 임원이 휴직했다는 말", body: "인사 소식은 확인이 어렵습니다. 경영진 능력에 대한 시장 평가가 흔들릴 수 있습니다." },
  { id: "r018", type: "CEO", tone: "positive", title: "{company}, 외부 스타 경영자를 영입한다는 이야기", body: "이름이 확인되지 않아 기대가 앞선 상태입니다." },
  { id: "r019", type: "제품", tone: "positive", title: "{company} 신제품 베타 반응이 예상보다 좋다는 캡처 확산", body: "캡처는 조작 가능성이 있습니다. 그래도 초기 커뮤니티 반응은 단기 수급을 움직입니다." },
  { id: "r020", type: "제품", tone: "negative", title: "{company} 신제품 출시가 미뤄졌다는 협력사발 소문", body: "납품 일정과 출시 일정은 다를 수 있습니다. 확인 전까지는 불확실성 재료입니다." },
  { id: "r021", type: "해킹", tone: "negative", title: "{company}, 보안 사고를 숨겼다는 주장", body: "정식 신고 기록은 없지만 평판 지표가 약한 기업에는 큰 부담입니다." },
  { id: "r022", type: "보안", tone: "positive", title: "{company}, 대형 보안 계약을 따냈다는 말", body: "해킹 공포가 커진 장세에서는 보안 관련 루머가 빠르게 퍼집니다." },
  { id: "r023", type: "소송", tone: "negative", title: "{company}, 전 파트너와 소송을 준비한다는 소문", body: "소송은 사실이어도 규모가 작을 수 있습니다. 법적리스크 수치가 높은 기업이 더 민감합니다." },
  { id: "r024", type: "수주", tone: "positive", title: "{company}, Market City 조달 평가에서 1순위라는 말", body: "평가 순위는 뒤집힐 수 있습니다. 정책 압력이 높은 업종일수록 변수가 많습니다." },
  { id: "r025", type: "회계", tone: "negative", title: "{company}, 회계 질의 대응이 늦어진다는 이야기", body: "단순 서류 보완일 수도 있지만 시장은 먼저 할인합니다." },
  { id: "r026", type: "투자", tone: "positive", title: "{company}, 비공개 전략 투자 유치 가능성", body: "투자 조건이 우호적인지 불리한지에 따라 결과는 정반대가 될 수 있습니다." },
  { id: "r027", type: "공장", tone: "positive", title: "{company}, 새 생산라인 시험 가동을 시작했다는 목격담", body: "목격담은 빠르지만 틀릴 수 있습니다. 실제 공시는 늦게 나옵니다." },
  { id: "r028", type: "공장", tone: "negative", title: "{company}, 생산라인 점검이 길어진다는 협력사 말", body: "점검이 지연인지 품질 강화인지는 확인되지 않았습니다." },
  { id: "r029", type: "파트너십", tone: "positive", title: "{company}, 전혀 다른 업종 기업과 공동 프로젝트 진행설", body: "시너지가 크면 재평가가 가능하지만 단순 마케팅일 수도 있습니다." },
  { id: "r030", type: "평판", tone: "negative", title: "{company}, 내부 만족도 급락이라는 익명 설문 유출", body: "익명 설문은 신뢰하기 어렵지만 경영진 능력 논쟁을 키울 수 있습니다." },
  { id: "r031", type: "수급", tone: "mixed", title: "{company}, 장중 이상 체결이 사전 정보 때문이라는 의혹", body: "이상 체결은 알고리즘 거래일 수도 있습니다. 루머 신뢰도 지표가 중요합니다." },
  { id: "r032", type: "정책", tone: "mixed", title: "{sector} 보조금 방향이 {company}에 유리하게 바뀐다는 말", body: "정책 문구 하나가 해석을 바꿀 수 있어 확인 전까지는 힌트에 가깝습니다." }
];

const disclosureTemplates = [
  { id: "d001", type: "배당 발표", tone: "positive", title: "{company}, 반기 배당 계획 공시", body: "이사회는 현금흐름과 투자 계획을 함께 고려해 배당안을 제시했습니다." },
  { id: "d002", type: "자사주 매입", tone: "positive", title: "{company}, 자사주 매입 신탁 계약 체결", body: "회사 측은 현재 가치가 내재 체력보다 낮게 평가됐다고 밝혔습니다." },
  { id: "d003", type: "유상증자", tone: "negative", title: "{company}, 운영자금 확보 목적 유상증자 결정", body: "신규 자금은 필요하지만 주식 수 증가 부담이 단기 수급에 영향을 줄 수 있습니다." },
  { id: "d004", type: "무상증자", tone: "positive", title: "{company}, 주주 친화 목적 무상증자 결의", body: "유동성 확대 효과가 기대되지만 기업 가치 자체가 바뀌는 것은 아닙니다." },
  { id: "d005", type: "CEO 교체", tone: "mixed", title: "{company}, 대표이사 변경 공시", body: "신임 경영진의 실행력과 기존 전략 유지 여부가 핵심입니다." },
  { id: "d006", type: "공장 증설", tone: "positive", title: "{company}, 생산 능력 확대를 위한 설비 투자", body: "수요 대응 목적의 투자지만 가동률이 올라오기 전까지 비용 부담이 남습니다." },
  { id: "d007", type: "실적 경고", tone: "negative", title: "{company}, 비용 증가에 따른 실적 전망 조정", body: "회사는 외부 변수와 선제 투자를 이유로 보수적 전망을 제시했습니다." },
  { id: "d008", type: "IPO", tone: "mixed", title: "{company} 관계사, IPO 예비 심사 신청", body: "관계사 가치 부각과 지분 희석 우려가 동시에 거론됩니다." },
  { id: "d009", type: "신규상장", tone: "mixed", title: "{sector} 신규상장 일정 확정 공시", body: "업종 관심은 높아지지만 기존 상장사에는 비교 압력이 생깁니다." },
  { id: "d010", type: "거래정지", tone: "negative", title: "{company}, 중요 공시 확인을 위한 거래정지", body: "정지 사유가 해소되기 전까지 투자 심리는 극도로 민감하게 움직입니다." },
  { id: "d011", type: "관리종목", tone: "negative", title: "{company}, 관리종목 지정 사유 발생", body: "회사는 개선 계획을 제출하겠다고 밝혔지만 시장 신뢰 회복에는 시간이 필요합니다." },
  { id: "d012", type: "상장폐지 심사", tone: "negative", title: "{company}, 상장폐지 실질심사 대상 여부 검토", body: "심사 결과가 나오기 전까지 거래와 평가에 큰 불확실성이 남습니다." },
  { id: "d013", type: "상장폐지", tone: "negative", title: "{company}, 상장폐지 결정 관련 이의 신청 예정", body: "절차상 반전 가능성은 있지만 위험도는 매우 높은 상태입니다." },
  { id: "d014", type: "인수합병", tone: "positive", title: "{company}, 전략적 인수합병 양해각서 체결", body: "최종 계약 전까지 가격과 조건은 변동될 수 있습니다." },
  { id: "d015", type: "회사분할", tone: "mixed", title: "{company}, 사업부 분할 검토 착수", body: "사업별 가치가 드러날 수 있지만 비용과 지배구조 논쟁이 뒤따릅니다." },
  { id: "d016", type: "합작법인", tone: "positive", title: "{company}, 공동 사업 추진을 위한 합작법인 설립", body: "초기 비용이 발생하지만 신규 시장 진입 가능성이 열립니다." },
  { id: "d017", type: "계약 해지", tone: "negative", title: "{company}, 주요 공급 계약 일부 해지", body: "단기 매출 공백이 생길 수 있으나 낮은 마진 계약 정리로 해석될 여지도 있습니다." },
  { id: "d018", type: "계약 체결", tone: "positive", title: "{company}, Market City 장기 공급 계약 체결", body: "장기 매출 가시성이 높아졌지만 실제 수익성은 단가 조건에 달려 있습니다." },
  { id: "d019", type: "소송", tone: "negative", title: "{company}, 손해배상 청구 소송 피소", body: "회사는 청구 금액이 과도하다고 밝혔지만 법적리스크가 커졌습니다." },
  { id: "d020", type: "소송 승소", tone: "positive", title: "{company}, 핵심 소송 1심 승소", body: "불확실성이 낮아졌지만 상대방 항소 가능성은 남아 있습니다." },
  { id: "d021", type: "회계 정정", tone: "negative", title: "{company}, 과거 매출 인식 일부 정정", body: "현금 유출은 제한적이지만 신뢰도에는 부담이 될 수 있습니다." },
  { id: "d022", type: "감사 의견", tone: "positive", title: "{company}, 감사 의견 적정 수령", body: "재무 불확실성이 일부 해소되며 위험 프리미엄이 낮아질 수 있습니다." },
  { id: "d023", type: "감사 의견", tone: "negative", title: "{company}, 감사 절차 지연 안내", body: "회사 측은 자료 보완 때문이라고 설명했지만 시장은 보수적으로 해석합니다." },
  { id: "d024", type: "투자 유치", tone: "positive", title: "{company}, 전략 투자자 대상 전환증권 발행", body: "투자 조건이 우호적이면 성장 재원으로 평가되지만 전환 물량 부담은 확인해야 합니다." },
  { id: "d025", type: "차입", tone: "negative", title: "{company}, 단기 차입금 증가 결정", body: "운전자금 확보 목적이지만 부채 부담이 높은 기업에는 할인 요인이 됩니다." },
  { id: "d026", type: "채무 상환", tone: "positive", title: "{company}, 고금리 차입금 조기 상환", body: "이자 부담이 줄어 현금흐름 개선 기대가 커졌습니다." },
  { id: "d027", type: "특허", tone: "positive", title: "{company}, 핵심 기술 특허 등록", body: "기술 방어력이 높아졌지만 상업화까지 이어지는지는 별도 확인이 필요합니다." },
  { id: "d028", type: "안전 인증", tone: "positive", title: "{company}, 주요 제품 안전 인증 획득", body: "규제 불확실성이 줄어 납품 일정이 빨라질 수 있습니다." },
  { id: "d029", type: "인증 지연", tone: "negative", title: "{company}, 인증 심사 일정 연기", body: "회사는 절차상 보완이라고 설명했지만 출시 일정에는 부담입니다." },
  { id: "d030", type: "임상", tone: "mixed", title: "{company}, 임상 중간 결과 제출", body: "일부 지표는 개선됐지만 최종 결론을 내리기에는 표본이 부족합니다." },
  { id: "d031", type: "파트너십", tone: "positive", title: "{company}, 타 업종 기업과 기술 제휴", body: "새로운 매출 경로가 열릴 수 있으나 계약 규모는 공개되지 않았습니다." },
  { id: "d032", type: "경영 계획", tone: "mixed", title: "{company}, 3개 라운드 경영 계획 공개", body: "성장 목표는 공격적이지만 자금 조달과 실행력이 변수입니다." }
];

const reportTemplates = [
  { id: "a001", stance: "긍정", rating: "비중확대", title: "{company}: 성장성은 유효, 가격 반응은 수급에 달림", body: "내부 체력은 개선되고 있으나 시장 심리와 고래 영향력이 단기 방향을 흔들 수 있습니다." },
  { id: "a002", stance: "중립", rating: "중립", title: "{company}: 좋은 회사와 좋은 진입점은 다르다", body: "펀더멘털은 나쁘지 않지만 이미 반영된 기대가 높아 이벤트 확인이 필요합니다." },
  { id: "a003", stance: "부정", rating: "비중축소", title: "{company}: 현금흐름이 먼저 확인되어야 한다", body: "성장 스토리보다 비용과 차입 부담이 투자 심리에 더 크게 작용하고 있습니다." },
  { id: "a004", stance: "중립", rating: "관망", title: "{company}: 루머보다 공시가 중요해지는 구간", body: "루머 신뢰도가 낮아져 확인된 문서가 나오기 전까지 변동성만 커질 수 있습니다." },
  { id: "a005", stance: "긍정", rating: "비중확대", title: "{sector} 자금 흐름 개선, {company} 재평가 가능", body: "업종 자금 유입이 이어지면 기업 고유 리스크보다 성장성이 먼저 가격에 반영될 수 있습니다." },
  { id: "a006", stance: "부정", rating: "비중축소", title: "{sector} 과열 신호, {company} 추격 매수 주의", body: "좋은 뉴스에도 매물이 나오는 구간입니다. 기대치가 높을수록 실망 위험도 커집니다." },
  { id: "a007", stance: "중립", rating: "중립", title: "{company}: 정책 변수의 방향이 아직 열려 있다", body: "정책 문구 하나가 수혜와 부담을 동시에 만들 수 있어 단정하기 어렵습니다." },
  { id: "a008", stance: "긍정", rating: "비중확대", title: "{company}: 경영진 실행력이 할인율을 낮출 수 있다", body: "관리 능력과 평판 지표가 개선되면 같은 실적에도 더 높은 평가를 받을 수 있습니다." },
  { id: "a009", stance: "부정", rating: "관망", title: "{company}: 법적리스크가 작은 악재를 키운다", body: "사건의 크기보다 시장이 의심하는 정도가 더 큰 문제가 될 수 있습니다." },
  { id: "a010", stance: "긍정", rating: "중립상향", title: "{company}: 악재 노출 후 위험 보상이 개선", body: "이미 공개된 악재가 가격에 반영됐다면 다음에는 해소 속도가 중요합니다." },
  { id: "a011", stance: "중립", rating: "중립", title: "{company}: 배당과 성장 사이의 균형점 탐색", body: "현금 환원은 안정감을 주지만 성장 투자를 늦출 수 있어 플레이어 성향에 따라 해석이 갈립니다." },
  { id: "a012", stance: "긍정", rating: "비중확대", title: "{company}: 혁신성 프리미엄은 아직 살아 있다", body: "기술 지표가 강한 기업은 작은 계약에도 기대가 빠르게 붙습니다." },
  { id: "a013", stance: "부정", rating: "비중축소", title: "{company}: 부채 부담이 선택지를 좁힌다", body: "자금 조달 조건이 불리해지면 좋은 사업도 희석 우려에 눌릴 수 있습니다." },
  { id: "a014", stance: "중립", rating: "관망", title: "{company}: 고래 영향력 확대, 판단 난도 상승", body: "대형 플레이어의 포지션 변화가 기업 가치보다 단기 가격에 더 큰 영향을 줄 수 있습니다." },
  { id: "a015", stance: "긍정", rating: "비중확대", title: "{company}: 기관 선호 조건에 가까워지고 있다", body: "현금흐름, 평판, 관리 능력의 조합이 개선되면 장기 자금 유입 가능성이 커집니다." },
  { id: "a016", stance: "부정", rating: "관망", title: "{company}: 성장률보다 신뢰 회복이 먼저다", body: "높은 성장성만으로는 부족합니다. 평판과 법적리스크가 할인율을 결정합니다." },
  { id: "a017", stance: "중립", rating: "중립", title: "{sector}: 정책 수혜와 규제 부담이 공존", body: "같은 업종 안에서도 기업 상태에 따라 결과가 다르게 나타날 수 있습니다." },
  { id: "a018", stance: "긍정", rating: "중립상향", title: "{company}: 공급망 안정화가 다음 촉매", body: "수요는 이미 확인됐고 이제는 납품 가능성과 비용 통제가 핵심입니다." },
  { id: "a019", stance: "부정", rating: "비중축소", title: "{company}: 신용 과열이 변동성을 키운다", body: "투자 심리는 강하지만 레버리지 비중이 높으면 좋은 뉴스에도 매도가 나올 수 있습니다." },
  { id: "a020", stance: "중립", rating: "관망", title: "{company}: 루머가 맞아도 가격은 다르게 움직일 수 있다", body: "사실 여부와 시장 반응은 별개입니다. 이미 반영된 기대가 더 중요할 때가 있습니다." },
  { id: "a021", stance: "긍정", rating: "비중확대", title: "{company}: 숨은 현금흐름 개선이 관측된다", body: "공식 숫자는 뒤늦게 확인되지만 선행 지표는 점진적으로 좋아지는 모습입니다." },
  { id: "a022", stance: "부정", rating: "관망", title: "{company}: 상장 리스크 프리미엄을 낮추기 어렵다", body: "관리종목이나 심사 관련 소문이 반복되면 작은 호재도 충분히 평가받기 어렵습니다." }
];

eventTypes.push("공모주 청약", "호가 변동 점검", "체결 과열", "ETF 추종 점검", "라운드 종료 변수");

newsTemplates.push(
  { id: "n057", type: "체결", tone: "mixed", title: "{company}, 실시간 체결량 급증에도 방향 해석 분산", body: "매수 체결이 많아 보여도 봇 유동성이나 단기 포지션 정리일 수 있습니다. 거래대금 증가가 실제 수요인지 확인이 필요합니다." },
  { id: "n058", type: "호가", tone: "mixed", title: "{company}, 호가 잔량 불균형 관측", body: "매도 잔량과 매수 잔량이 한쪽으로 기울었지만 허수 주문 가능성도 있어 즉시 방향으로 단정하기 어렵습니다." },
  { id: "n059", type: "공모주", tone: "mixed", title: "{sector} 공모주 관심 확대, {company}에는 비교 부담", body: "신규상장 기대가 업종 관심을 키우지만 기존 종목의 자금이 빠져나갈 수도 있습니다. 과열 온도가 핵심 변수입니다." },
  { id: "n060", type: "ETF", tone: "mixed", title: "마켓 인버스·레버리지 수요 증가, {company} 단기 변동성 확대", body: "지수 추종 상품으로 자금이 이동하면 개별 기업 재료보다 시장 방향 베팅이 먼저 가격을 흔들 수 있습니다." },
  { id: "n061", type: "랭킹심리", tone: "mixed", title: "상위권 플레이어 방어 움직임, {company} 수급 판단 어려워져", body: "라운드 순위 경쟁이 강해지면 기업 가치와 무관한 매수·매도가 섞입니다. 누가 왜 움직이는지 추정해야 합니다." },
  { id: "n062", type: "상한하한", tone: "mixed", title: "{company}, 가격제한폭 근처 접근 후 매물 소화 시험", body: "상한가나 하한가 근처에서는 좋은 뉴스도 체결 공백 때문에 다르게 보일 수 있습니다. 잔량과 거래대금이 같이 중요합니다." },
  { id: "n063", type: "봇수급", tone: "mixed", title: "봇 트레이더 체결이 {company} 분위기를 흔드는 중", body: "개미부대, 기관, 스캘퍼성 체결이 섞이며 체결 로그가 시끄러워졌습니다. 실제 플레이어 압력과 구분할 필요가 있습니다." },
  { id: "n064", type: "시초가", tone: "mixed", title: "{company}, 기준가 대비 괴리 확대", body: "시초가 대비 괴리가 커졌지만 추세인지 과열인지는 불명확합니다. 고가·저가 범위를 함께 봐야 합니다." }
);

rumorTemplates.push(
  { id: "r033", type: "체결", tone: "mixed", title: "{company}, 특정 플레이어가 몰래 물량을 모은다는 말", body: "체결 로그 일부만 보고 나온 추정입니다. 실제로는 봇 거래나 분할 매도일 수 있습니다." },
  { id: "r034", type: "공모주", tone: "mixed", title: "{company} 관련 공모주 청약 경쟁률이 높다는 소문", body: "경쟁률 숫자는 확인되지 않았습니다. 높아도 상장 당일 차익실현이 강할 수 있습니다." },
  { id: "r035", type: "호가", tone: "negative", title: "{company}, 매도벽 뒤에 숨은 악재가 있다는 게시글", body: "큰 매도 잔량은 심리 압박일 수도, 단순 호가 장난일 수도 있습니다. 출처가 약합니다." },
  { id: "r036", type: "ETF", tone: "mixed", title: "마켓 레버리지2X 자금이 {sector} 쪽으로 번진다는 말", body: "지수 베팅이 개별 종목 매수로 이어질지는 확인되지 않았습니다. 시장 심리와 유동성에 따라 달라집니다." },
  { id: "r037", type: "순위", tone: "mixed", title: "상위권 플레이어가 {company}를 방어주로 쓴다는 추정", body: "보유 현황이 공개되지 않은 상태의 추정입니다. 따라 들어가면 출구가 막힐 수 있습니다." }
);

disclosureTemplates.push(
  { id: "d033", type: "공모주 청약", tone: "mixed", title: "{company}, 공모주 청약 일정 안내", body: "청약 관심은 높지만 상장 후 유통 물량과 라운드 유동성에 따라 반응이 크게 달라질 수 있습니다." },
  { id: "d034", type: "거래정지", tone: "negative", title: "{company}, 호가 급변 관련 조회공시 요구", body: "급변 사유 확인 전까지 거래 심리가 얼어붙을 수 있습니다. 해명 내용이 나오면 반대로 움직일 여지도 있습니다." },
  { id: "d035", type: "ETF 추종 점검", tone: "mixed", title: "마켓 인버스·레버리지 괴리율 점검 공시", body: "지수 상품의 추적오차가 커졌습니다. 개별 종목 뉴스보다 시장 방향 베팅이 강해진 신호일 수 있습니다." },
  { id: "d036", type: "체결 과열", tone: "mixed", title: "{company}, 단기과열 완화 장치 발동 예고", body: "과열 완화는 부담이지만 과도한 속도를 줄여 오히려 다음 라운드 불확실성을 낮출 수 있습니다." }
);

reportTemplates.push(
  { id: "a023", stance: "중립", rating: "관망", title: "{company}: 체결 로그는 힌트이지 결론이 아니다", body: "거래량과 체결 방향이 같아 보여도 봇, 플레이어 압력, 차익실현이 섞이면 가격 반응은 반대로 나올 수 있습니다." },
  { id: "a024", stance: "중립", rating: "중립", title: "{sector}: 공모주 과열은 기존 종목에 양날의 칼", body: "신규상장 기대는 업종 관심을 만들지만 기존 종목의 자금 집중도를 낮출 수 있습니다." },
  { id: "a025", stance: "부정", rating: "관망", title: "{company}: 호가 잔량만 보고 따라가기 어려운 구간", body: "큰 잔량은 지지선이나 저항선처럼 보이지만 실제 체결 의지가 없는 주문일 수 있습니다." },
  { id: "a026", stance: "긍정", rating: "중립상향", title: "{company}: 악재 확인 뒤 수급 안정 여부가 관건", body: "부담 재료가 공개된 뒤에도 거래대금이 유지되면 시장은 해소 쪽으로 해석할 수 있습니다." }
);

window.MarketData = {
  companies,
  marketState,
  sectorStates,
  eventTypes,
  newsTemplates,
  rumorTemplates,
  disclosureTemplates,
  reportTemplates
};
